# Site settings
title: ToodullToodull developer
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://github.com/kimsojeong1225/kimsojeong1225.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: kimsojeong1225
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Engineer
email: chgml09255@gmail.com
# twitter_username: lorem_ipsum
# github_username:  kimsojeong1225
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
